/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Student, ChecklistItem, HomeVisitRecord } from './types';

// พิกัดจำลองรอบๆ โรงเรียนบ้านจันทน์หอมตาเสก
export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'STD001',
    studentIdCard: '61001',
    studentCode: '61001',
    prefix: 'ด.ช.',
    name: 'ด.ช. ณัฐดนัย สมบูรณ์ทรัพย์',
    nickname: 'น็อต',
    gender: 'ชาย',
    birthDate: '15/05/2544',
    grade: 'ม.3/2',
    room: '2',
    citizenId: '1339900000001',
    address: '42/1 ซอยลาดพร้าว 48 แขวงสามเสนนอก เขตห้วยขวาง กรุงเทพฯ 10310',
    latitude: 13.7915,
    longitude: 100.5742,
    visitStatus: 'visited',
    riskLevel: 'normal',
    lastVisitedDate: '2569-05-15',
    parentName: 'นางกาญจนา สมบูรณ์ทรัพย์',
    parentRelation: 'มารดา',
    parentPhone: '081-234-5678',
    parentJob: 'ค้าขาย',
    guardianName: 'นางกาญจนา สมบูรณ์ทรัพย์',
    guardianRelation: 'มารดา',
    phone: '081-234-5678',
  },
  {
    id: 'STD002',
    studentIdCard: '61002',
    studentCode: '61002',
    prefix: 'ด.ญ.',
    name: 'ด.ญ. พิชชาภา เลิศวิจิตร',
    nickname: 'แก้ม',
    gender: 'หญิง',
    birthDate: '22/08/2544',
    grade: 'ม.3/2',
    room: '2',
    citizenId: '1339900000002',
    address: '15/3 ซอยรัชดาภิเษก 32 แขวงจันทรเกษม เขตจตุจักร กรุงเทพฯ 10900',
    latitude: 13.8052,
    longitude: 100.5821,
    visitStatus: 'pending',
    riskLevel: 'not_assessed',
    lastVisitedDate: null,
    parentName: 'นายประสิทธิ์ เลิศวิจิตร',
    parentRelation: 'บิดา',
    parentPhone: '089-876-5432',
    parentJob: 'รับจ้างทั่วไป',
    guardianName: 'นายประสิทธิ์ เลิศวิจิตร',
    guardianRelation: 'บิดา',
    phone: '089-876-5432',
  },
  {
    id: 'STD003',
    studentIdCard: '61003',
    studentCode: '61003',
    prefix: 'ด.ช.',
    name: 'ด.ช. ศุภณัฐ ขยันหาญ',
    nickname: 'ปอนด์',
    gender: 'ชาย',
    birthDate: '10/11/2544',
    grade: 'ม.3/2',
    room: '2',
    citizenId: '1339900000003',
    address: '99/4 ชุมชนริมคลองลาดพร้าว แขวงสามเสนนอก เขตห้วยขวาง กรุงเทพฯ 10310',
    latitude: 13.7841,
    longitude: 100.5895,
    visitStatus: 'visited',
    riskLevel: 'high',
    lastVisitedDate: '2569-05-20',
    parentName: 'ยายสมใจ ใจอารีย์',
    parentRelation: 'ยาย',
    parentPhone: '086-555-1234',
    parentJob: 'เกษตรกรปอกกระเทียม',
    guardianName: 'ยายสมใจ ใจอารีย์',
    guardianRelation: 'ยาย',
    phone: '086-555-1234',
  },
  {
    id: 'STD004',
    studentIdCard: '61004',
    studentCode: '61004',
    prefix: 'ด.ญ.',
    name: 'ด.ญ. โชติกา พิมพิลา',
    nickname: 'น้ำอุ่น',
    gender: 'หญิง',
    birthDate: '01/01/2545',
    grade: 'ม.3/2',
    room: '2',
    citizenId: '1339900000004',
    address: '124 ซอยโชคชัย 4 แขวงสะพานสอง เขตวังทองหลาง กรุงเทพฯ 10310',
    latitude: 13.7988,
    longitude: 100.5963,
    visitStatus: 'scheduled',
    riskLevel: 'not_assessed',
    lastVisitedDate: null,
    parentName: 'นางอำพร พิมพิลา',
    parentRelation: 'มารดา',
    parentPhone: '085-111-9988',
    parentJob: 'พนักงานบริษัท',
    guardianName: 'นางอำพร พิมพิลา',
    guardianRelation: 'มารดา',
    phone: '085-111-9988',
  },
  {
    id: 'STD005',
    studentIdCard: '61005',
    studentCode: '61005',
    prefix: 'ด.ญ.',
    name: 'ด.ญ. อริสรา จันทร์สว่าง',
    nickname: 'มายด์',
    gender: 'หญิง',
    birthDate: '05/04/2544',
    grade: 'ม.3/2',
    room: '2',
    citizenId: '1339900000005',
    address: '88/12 ซอยประดิษฐ์มนูธรรม 15 แขวงลาดพร้าว เขตลาดพร้าว กรุงเทพฯ 10230',
    latitude: 13.8115,
    longitude: 100.6012,
    visitStatus: 'visited',
    riskLevel: 'medium',
    lastVisitedDate: '2569-05-28',
    parentName: 'นางวิภา จันทร์สว่าง',
    parentRelation: 'ป้า',
    parentPhone: '082-990-2211',
    parentJob: 'พนักงานห้างสรรพสินค้า',
    guardianName: 'นางวิภา จันทร์สว่าง',
    guardianRelation: 'ป้า',
    phone: '082-990-2211',
  },
];

export const INITIAL_VISIT_RECORDS: HomeVisitRecord[] = [
  {
    id: 'REC001',
    studentId: 'STD001',
    visitedDate: '2026-05-15',
    semester: '1',
    schoolYear: '2569',
    visitorName: 'ครูสมศรี มีปัญญา',
    informantName: 'นางกาญจนา สมบูรณ์ทรัพย์',
    informantRelation: 'มารดา',
    
    familyStatus: 'พ่อแม่อยู่ด้วยกัน',
    livingWith: 'พ่อ/แม่',
    guardianName: 'นางกาญจนา สมบูรณ์ทรัพย์',
    guardianRelation: 'มารดา',
    guardianCitizenId: '3339900001234',
    guardianEducation: 'มัธยมศึกษาปีที่ 3',
    guardianJob: 'ค้าขาย',
    guardianPhone: '081-234-5678',
    stateWelfare: 'ไม่ได้สวัสดิการแห่งรัฐ',
    totalMembers: 4,
    
    houseOwnership: 'บ้านตนเอง',
    monthlyRent: 0,
    floorMaterial: 'ปูน/กระเบื้อง',
    wallMaterial: 'ปูน/อิฐ',
    roofMaterial: 'กระเบื้องลอน',
    hasToilet: 'มี',
    farmLand: 0,
    waterSource: 'น้ำประปา',
    electricity: 'มีไฟฟ้าใช้',
    vehicles: 'รถจักรยานยนต์ 2 คัน',
    
    travelMethod: 'รถจักรยานยนต์',
    travelDistance: 5.5,
    travelTime: '15 นาที',
    travelCost: 300,
    dailyAllowance: 60,
    homeAddress: 'บ้านเลขที่ 42/1 หมู่ที่ 2 ซอยลาดพร้าว 48 แขวงสามเสนนอก เขตห้วยขวาง กรุงเทพฯ 10310',
    
    latitude: 13.7915,
    longitude: 100.5742,
    
    studentImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=200',
    outsideImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=400',
    insideImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=400',
    
    signatureStudent: 'data:image/svg+xml;utf8,<svg viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg"><path d="M10,15 Q30,5 50,20 T90,10" fill="none" stroke="black" stroke-width="2"/></svg>',
    signatureParent: 'data:image/svg+xml;utf8,<svg viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg"><path d="M8,10 C25,25 45,5 85,15" fill="none" stroke="black" stroke-width="2"/></svg>',
    signatureTeacher: 'data:image/svg+xml;utf8,<svg viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg"><path d="M5,18 C30,2 60,28 95,12" fill="none" stroke="black" stroke-width="2"/></svg>',
    signatureGov: 'data:image/svg+xml;utf8,<svg viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg"><path d="M15,15 Q50,0 85,25" fill="none" stroke="black" stroke-width="2"/></svg>',
    signatureDirector: 'data:image/svg+xml;utf8,<svg viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg"><path d="M10,10 C40,30 70,-10 90,20" fill="none" stroke="black" stroke-width="2"/></svg>',
    
    teacherName: 'ครูสมศรี มีปัญญา',
    directorName: 'นายณรงค์วิทย์ สุวรรณศรี',
    govName: 'นายประสิทธิ์ สุขแสน',
    govPosition: 'นายก อบต. จันทน์หอม',
    
    note: 'มีผู้สูงอายุในบ้านช่วยพึ่งพิง 1 คน ได้รับสวัสดิการเบี้ยยังชีพคนชรา',
    members: [
      { memberId: 'M001', fullName: 'ด.ช. ณัฐดนัย สมบูรณ์ทรัพย์', relation: 'ตัวนักเรียน', citizenId: '1339900000001', age: '15', totalIncome: 0 },
      { memberId: 'M002', fullName: 'นายสมเกียรติ สมบูรณ์ทรัพย์', relation: 'บิดา', citizenId: '3339900001222', age: '45', totalIncome: 12000 },
      { memberId: 'M003', fullName: 'นางกาญจนา สมบูรณ์ทรัพย์', relation: 'มารดา', citizenId: '3339900001234', age: '42', totalIncome: 6000 },
      { memberId: 'M004', fullName: 'นางสมใจ สมบูรณ์ทรัพย์', relation: 'คุณหมอ/คุณยาย', citizenId: '3339900001555', age: '68', totalIncome: 700 }
    ],
    createdAt: '2026-05-15T10:00:00Z',
    manualRiskAssessment: 'normal',
    manualActionNotes: 'สนับสนุนเรื่องการเรียนต่อ ม.4 ในหลักสูตรที่นักเรียนสนใจ จัดส่งประเมินคัดเลือกรักเรียนทุนดีเด่นของโรงเรียน',
    aiAnalysis: {
      summary: 'ครอบครัวมีความสุข ปลอดภัย และดูแลสนับสนุนลูกเป็นเลิศ มีสภาพแวดล้อมที่เหมาะสมกับการศึกษาและการเติบโตอย่างมีคุณภาพ',
      strengths: ['แม่มีเวลาให้ลูกสม่ำเสมอ', 'นักเรียนมีความรับผิดชอบ ช่วยเหงานบ้าน', 'ที่พักอาศัยมั่นคงและถูกสุขลักษณะ'],
      challenges: ['รายได้ผู้ปกครองผันแปรตามสภาวะตลาดค้าขาย'],
      riskLevel: 'normal',
      actionPlan: 'ส่งเสริมสิทธิทุนการศึกษานักเรียนเรียนดี และสนับสนุนแนะแนวศึกษาต่อระดับชั้นมัธยมปลายแยกเฉพาะ',
      suggestedHelp: ['ทุนนักเรียนเรียนดี', 'โควตาแนะแนวศึกษาต่อต่างจังหวัด'],
      assessedAt: '2026-05-15T10:00:00Z',
    },
  },
  {
    id: 'REC003',
    studentId: 'STD003',
    visitedDate: '2026-05-20',
    semester: '1',
    schoolYear: '2569',
    visitorName: 'ครูสมศรี มีปัญญา',
    informantName: 'ยายสมใจ ใจอารีย์',
    informantRelation: 'ยาย',
    
    familyStatus: 'บิดา/มารดาเสียชีวิต',
    livingWith: 'ญาติ',
    guardianName: 'ยายสมใจ ใจอารีย์',
    guardianRelation: 'ยาย',
    guardianCitizenId: '5339900004321',
    guardianEducation: 'ประถมศึกษาปีที่ 4',
    guardianJob: 'เกษตรกรปอกกระเทียม',
    guardianPhone: '086-555-1234',
    stateWelfare: 'ได้รับสวัสดิการแห่งรัฐ',
    totalMembers: 2,
    
    houseOwnership: 'บ้านเช่า',
    monthlyRent: 800,
    floorMaterial: 'ดิน/ไม้ไผ่',
    wallMaterial: 'ไม้ไผ่/ใบจาก/สังกะสีเก่า',
    roofMaterial: 'สังกะสีเก่า/ใบจาก',
    hasToilet: 'ไม่มี',
    farmLand: 0,
    waterSource: 'น้ำฝน/บ่อ',
    electricity: 'มีไฟฟ้าใช้',
    vehicles: 'ไม่มี',
    
    travelMethod: 'เดิน',
    travelDistance: 3.0,
    travelTime: '40 นาที',
    travelCost: 0,
    dailyAllowance: 20,
    homeAddress: 'บ้านเลขที่ 99/4 หมู่ที่ 7 แขวงสามเสนนอก เขตห้วยขวาง กรุงเทพฯ 10310',
    
    latitude: 13.7841,
    longitude: 100.5895,
    
    studentImage: 'https://images.unsplash.com/photo-1544717297-fa95b6ee9643?auto=format&fit=crop&q=80&w=200',
    outsideImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=400',
    insideImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=400',
    
    signatureStudent: 'data:image/svg+xml;utf8,<svg viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg"><path d="M10,12 Q30,22 80,10" fill="none" stroke="black" stroke-width="2"/></svg>',
    signatureParent: 'data:image/svg+xml;utf8,<svg viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg"><path d="M5,15 Q40,5 95,25" fill="none" stroke="black" stroke-width="2"/></svg>',
    signatureTeacher: 'data:image/svg+xml;utf8,<svg viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg"><path d="M5,18 C30,2 60,28 95,12" fill="none" stroke="black" stroke-width="2"/></svg>',
    signatureGov: 'data:image/svg+xml;utf8,<svg viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg"><path d="M15,15 Q50,0 85,25" fill="none" stroke="black" stroke-width="2"/></svg>',
    signatureDirector: 'data:image/svg+xml;utf8,<svg viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg"><path d="M10,10 C40,30 70,-10 90,20" fill="none" stroke="black" stroke-width="2"/></svg>',
    
    teacherName: 'ครูสมศรี มีปัญญา',
    directorName: 'นายณรงค์วิทย์ สุวรรณศรี',
    govName: 'นายประสิทธิ์ สุขแสน',
    govPosition: 'นายก อบต. จันทน์หอม',
    
    note: 'ภาระพึ่งพิง: มีผู้สูงอายุ, ผู้ป่วยเรื้อรังปวดหลังเสื่อมสภาพทำงานหนักไม่ได้',
    members: [
      { memberId: 'M101', fullName: 'ด.ช. ศุภณัฐ ขยันหาญ', relation: 'ตัวนักเรียน', citizenId: '1339900000003', age: '14', totalIncome: 0 },
      { memberId: 'M102', fullName: 'ยายสมใจ ใจอารีย์', relation: 'คุณยาย', citizenId: '5339900004321', age: '72', totalIncome: 1400 }
    ],
    createdAt: '2026-05-20T14:30:00Z',
    manualRiskAssessment: 'high',
    manualActionNotes: 'เร่งดำเนินการสมัครทุนนักเรียนยากจนเงื่อนไขยากจนพิเศษ (กสศ.) ทันที จัดหาเครื่องอุปโภคบริโภคช่วยเหลือครอบครัวเบื้องต้นและประสานครูแนะเพื่อปรับพฤติกรรมการเล่นเกม',
    aiAnalysis: {
      summary: 'นักเรียนตกอยู่ในสภาพวิกฤตทางเศรษฐกิจ ไม่มีพ่อแม่เลี้ยงดู ยายอายุมากสภาพบ้านทรุดโทรมไม่ปลอดภัย ทั้งยังมีประเด็นติดเกม โทรศัพท์ และขาดแคลนด้านการเรียนรู้อย่างหนัก เสี่ยงสูงต่อการออกจากโรงเรียน',
      strengths: ['นักเรียนยังคงอาศัยอยู่กับคุณยายและช่วยงานบ้าง', 'โรงเรียนเข้าถึงพิกัดบ้านเพื่อประเมินสถานการณ์ได้รวดเร็ว'],
      challenges: ['รายได้รวมของครอบครัวต่ำกว่าเกณฑ์ยากจนพิเศษมาก', 'สภาพบ้านไม่ปลอดภัย มีความเป็นอยู่เสี่ยงอันตรายด้านร่างกายและอนามัย', 'พฤติกรรมติดเกมนอนดึกส่งผลไม่ทัศนศึกษาในห้องเรียน'],
      riskLevel: 'high',
      actionPlan: 'จัดทำเรื่องส่งต่อกองทุน กสศ. เร่งด่วน, ประสานจัดหาอาหารกลางวันสำรองกลับบ้านพัก, ประเมินสุขภาพจิตนัดแนะครูแนะแนวร่วมปรับตัวนักเรียน',
      suggestedHelp: ['ทุนยากจนพิเศษ (กสศ.)', 'ถุงยังชีพและของยังชีพบรรเทาทุกข์', 'วิทยากรแนะแนวป้องกันเกมและพัฒนาทักษะอาชีพ'],
      assessedAt: '2026-05-20T14:30:00Z',
    },
  },
];

export const INITIAL_CHECKLIST: ChecklistItem[] = [
  { id: 'CHK001', task: 'ประชุมวางแผนทีมงานครูประจำชั้นและผู้บริหาร', category: 'prepare', completed: true },
  { id: 'CHK002', task: 'นัดหมายแจ้งกำหนดการเยี่ยมบ้านกับผู้ปกครองล่วงหน้า', category: 'prepare', completed: true },
  { id: 'CHK003', task: 'เตรียมเอกสารแบบฟอร์มบันทึก, แฟ้มแฟ้มสะสมงานของนักเรียน', category: 'prepare', completed: true },
  { id: 'CHK004', task: 'ศึกษาประวัตินักเรียนเดิม ผลการเรียน และบันทึกประเมินพฤติกรรม SDQ เล็กน้อยก่อนออกตรวจ', category: 'prepare', completed: false },
  { id: 'CHK005', task: 'สัมภาษณ์พูดคุยผู้ปกครองเพื่อเก็บข้อมูลและสร้างความสัมพันธ์ที่ดี', category: 'on_visit', completed: true },
  { id: 'CHK006', task: 'สังเกตสภาพแวดล้อมที่ตั้งบ้าน ความเป็นอยู่ และสุขลักษณะห้องนอน/ห้องนอน', category: 'on_visit', completed: true },
  { id: 'CHK007', task: 'ถ่ายรูปภาพร่วมกับผู้ปกครองและนักเรียนเป็นหลักฐาน', category: 'on_visit', completed: true },
  { id: 'CHK008', task: 'บันทึกพิกัดตำแหน่งบ้าน (ละติจูด, ลองจิจูด)', category: 'on_visit', completed: false },
  { id: 'CHK009', task: 'สรุปประเมินความเสี่ยงและคัดกรองแยกนักเรียนกรณี กลุ่มปกติ/เสี่ยง/มีปัญหา', category: 'after_visit', completed: true },
  { id: 'CHK010', task: 'ส่งบันทึกรายงานให้ผู้บริหารเพื่อรับทราบผลการวิเคราะห์และอนุมัติความช่วยเหลือ', category: 'after_visit', completed: false },
  { id: 'CHK011', task: 'ส่งต่อกรณีกิจกรรมแนะแนว หรือ กิจกรรมปกครองป้องปรามนักเรียนเป็นรายกรณีตามพบปัญหา', category: 'after_visit', completed: false },
];
